spring.application.name=expense-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=Ryback@9098
server.port=8085

app.jwt.secret=01234567890123456789012345678901
app.jwt.expiration-ms=86400000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect